### PR TITLE
Update worldmaps contrib-type

### PR DESCRIPTION
**Pull request by mrkubax10**

### CODE REVIEW

**Comment by Semphriss** [comment]
diff?

**Comment by mrkubax10** [comment]
How can I do that?

**Comment by Semphriss** [comment]
Extract the .zips from `master`, do the same from your PR branch, then use `diff` between them

**Comment by mrkubax10** [comment]
[addons.txt](https://github.com/SuperTux/addons/files/8010974/addons.txt)

**Pull request closed without merging**
