### PR TITLE
Fix backgrounds + misc in Island of Moob

### PR DESCRIPTION
**Pull request by toberge**
- Swapped backgrounds that were using old filepaths and thus did not render
  properly
- Replaced some backgrounds with gradients since there did not seem to
  be viable alternatives to the backgrounds that have been removed
- Expand the first sector of the quiz level to avoid black bars in
  fullscreen at 1080p
- Adjusted the placement of some spawn points in the Tower of Moob level

See the [related PR in the addons-src repo](https://github.com/SuperTux/addons-src/pull/15)

### CODE REVIEW

**Comment by Vankata453** [comment]
This updates the worldmap in the "Worldmaps/" directory, which is unused. The addon needs to be updated in the "repository" directory, by adding a new version and editing the URL, version and MD5 hash in "index_0-6.nfo" file.

**Comment by Vankata453** [comment]
I am planning to open a pull request, which does re-organization to the repository + adds some important changes for future versions, like the new `contrib-type` property to add-ons. If you agree, I can commit your changes there directly.

**Comment by toberge** [comment]
> I am planning to open a pull request, which does re-organization to the repository + adds some important changes for future versions, like the new `contrib-type` property to add-ons. If you agree, I can commit your changes there directly.

That's fine with me, it does seem like this repo needs some spring-cleaning. I did at least put the archive file where it should be now.

**Comment by Vankata453** [comment]
> > I am planning to open a pull request, which does re-organization to the repository + adds some important changes for future versions, like the new `contrib-type` property to add-ons. If you agree, I can commit your changes there directly.
> 
> That's fine with me, it does seem like this repo needs some spring-cleaning. I did at least put the archive file where it should be now.

Alright, I will include the changes, as well as the `contrib-type` addition. 👍

**Comment by weluvgoatz** [comment]
Included in #37

**Pull request closed without merging**
