### PR TITLE
Updated Hume's worlds

### PR DESCRIPTION
**Pull request by Hume2**
Someone just has to update the index.nfo.

### CODE REVIEW

**Comment by maxteufel** [comment]
`repository/hume-worldmaps_v1.zip` also needs an update, as far as I can see (which is used for the 0.4.0+ Add-ons).

Updating the `index.nfo`s is just updating the MD5 hash sums and the versions.

**Comment by Hume2** [comment]
@mt Why is there the .zip twice?

**Comment by maxteufel** [comment]
Due to the version differences I think (also don't @mention any random GitHub user).

**Comment by maxteufel** [comment]
If this resolves #8, #9, #10, please add `Closes #8, closes #9 and closes #10`  in commit message's **body**.

**Comment by Hume2** [comment]
Now just the index.nfo

**Comment by Hume2** [comment]
I hope that the MD5 is correct. Better check it out.

**Pull request closed without merging**
